"use client";

import { useMemo } from "react";
import { markdownToHtml } from "@/lib/markdown";
import ChatBubbleContent from "@/app/summary/[id]/components/ChatBubbleContent";
import { BotIco, UserIco } from "@/app/components/icons";

/**
 * Read-only summary + chat thread for public share pages.
 */
export default function SharedConversationView({ snapshot }) {
  const summaryHtml = useMemo(() => {
    const out = snapshot?.summaryOutput?.trim() || "";
    if (!out) return "";
    return markdownToHtml(out);
  }, [snapshot?.summaryOutput]);

  const messages = snapshot?.messages || [];

  return (
    <article className="chat-share-article">
      {summaryHtml ? (
        <section className="chat-share-summary">
          <h2 className="chat-share-section-label">Summary</h2>
          <div
            className="sum-text md chat-share-summary-body"
            dangerouslySetInnerHTML={{ __html: summaryHtml }}
          />
        </section>
      ) : null}

      {messages.length > 0 ? (
        <section className="chat-share-chat">
          <h2 className="chat-share-section-label">Conversation</h2>
          <div className="chat-thread">
            {messages.map((m, i) => {
              const role = m.role === "assistant" ? "ai" : "user";
              return (
                <div key={i} className={`m-row ${role}`}>
                  <div className={`m-ava ${role}`}>
                    {role === "ai" ? <BotIco /> : <UserIco />}
                  </div>
                  <div className="m-bub-wrap">
                    <div className="m-bub-col">
                      <div className={`m-bub ${role} md`}>
                        <ChatBubbleContent mdSrc={m.content || ""} />
                      </div>
                      {role === "ai" && m.modelLabel ? (
                        <div className="m-meta">
                          Generated by {m.modelLabel}
                        </div>
                      ) : null}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      ) : null}
    </article>
  );
}
